- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/main.rs
Just like https://github.com/profianinc/steward/pull/44 https://github.com/profianinc/drawbridge/pull/215
Added `openidconnect` dependency, since that's what we'll use for #11
> feat: add TOML configuration functionality

- src/main.rs
Resolves: #9
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
> feat: add a configurable timeout

- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/main.rs
This defaults to the number of hardware threads on the CPU.
Resolves: #26
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
> feat: add configurable maximum jobs

- src/uuid_get.html
We all were wondering about the missing output.
Signed-off-by: Harald Hoyer <harald@profian.com>
> feat: also output stderr in the console

- src/main.rs
This is required for security, since we do not want to expose the secret on command line or in a config file
> feat: read OIDC secret from a file

- src/main.rs
> feat: only allow users who created jobs to view them

- src/root_get.html
> fix: frontend login

- src/auth.rs
- src/main.rs
- src/redirect.rs
- src/root_get.html
Closes #48
edit: i added a period to the end of "..Wasm workloads." but I'm not going to retake screenshots
edit2 handle more errors:
> feat: handle errors in a more dynamic and user friendly way

- src/auth.rs
- src/redirect.rs
- src/templates.rs
- templates/root_get.html
- templates/uuid_get.html
blocked by: https://github.com/profianinc/benefice/pull/62
> chore: add SPDX license headers to source files

- templates/root_get.html
- templates/uuid_get.html
Create a better UI for last page so users can navigate elsewhere.
Fixes #66 
> feat: enhance last page

- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/auth.rs
- src/github.rs
- src/main.rs
- src/templates.rs
- templates/root_get.html
> feat: allow starred users to have benefits

- templates/root_get.html
- templates/uuid_get.html
> fix: optimize css and icons

- templates/idx.html
- templates/job.html
- Add img alt for Enarx/Profian logos
- Fix Join Community link
- Change Wasm gallery description
> fix: add minor accessibility improvements

- templates/job.html
Add Initiatives column to footer, so that it matches Enarx.dev footer.
> docs: update footer

- Cargo.lock
- Cargo.nix
- Cargo.toml
- examples.txt
- src/auth/user.rs
- src/jobs.rs
- src/main.rs
- src/templates.rs
- templates/idx.html
- templates/job.html
Closes #27
many of the included demos take a long time to start or have other issues, that's out of scope for this PR but I can remove them if required
> feat: add drawbridge integration

- templates/idx.html
- templates/job.html
> docs: review text

- templates/idx.html
Add a very succinct description of Drawbridge. We can add a link later to provide more detail.
> docs: define Drawbridge

- templates/idx.html
> fix: hack navbar to always show the login/logout button

- src/job.rs
- src/main.rs
Revive `command` argument removed in e4c3d7d6897f4e420afe821a32880f890633a5a3
Allow usage of arbitrary OCI container engine, which is usually either
docker or podman
> fix: avoid hardcoding `docker`

- LICENSE
- src/auth/key.rs
> chore: add license file and fix inconsistent SPDX header

- examples.txt
Related to #132
I need to investigate this further to determine whats going on
> fix: disable greenhouse-monitor-csharp for now

- src/job.rs
- src/main.rs
> feat: allow the oci image tag to be configurable

- src/job.rs
Closes #131 
ENARX_BACKEND="fdjnuuerwfghufwe"
> feat: pass ENARX_BACKEND to enarx docker container

- templates/idx.html
> fix: login/logout buttons not showing/hiding properly

- src/job.rs
- src/main.rs
> feat: support passing devices into the container

- src/job.rs
- src/main.rs
> feat: support TEEs

- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/main.rs
Rely on https://github.com/rvolosatovs/confargs for parsing arguments
This adds support for parsing arrays from the config
> feat: use `confargs` for argument parsing

- src/job.rs
Rather than attempting to parse the output as a valid socket address,
only parse the port directly.
This ensures addresses of form `1.2.3.4%lo:12345` are correctly handled.
> fix: avoid parsing addresses as socket addresses

- src/main.rs
- templates/idx.html
> fix: prevent old output appearing when restarting jobs

- src/auth/mod.rs
- src/auth/user.rs
- src/main.rs
Closes #71
Thanks @puiterwijk for helping with this
> feat: check the has_starred_enarx claim in the OIDC id token

- src/main.rs
- src/templates.rs
- templates/idx.html
Code change to allow #162 to be fixed
> feat: allow the port links to be on a customizable domain name

- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/main.rs
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
> feat: add structured logging for request/response

- Cargo.lock
- Cargo.nix
- Cargo.toml
- src/auth/mod.rs
- src/auth/user.rs
- src/main.rs
- templates/idx.html
> fix: redirect users to the last viewed page after login/logout

- templates/idx.html
Closes #163
Also fixes some other frontend issues
> feat: improve the unauthenticated user experience

- src/main.rs
This adds a request_id field (with a random v4 UUID) to the span of every request, which makes it possible to correlate different log entries that belong to a single request.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
> feat: include request_id in logs

- src/job.rs
- src/main.rs
- templates/idx.html
Closes #174
If tcp then link as `http://localhost:3424`
If tls then link as `https://localhost:3424`
> feat: link ports as https/http if tls/tcp respectively

- src/auth/mod.rs
- src/job.rs
- src/main.rs
This makes use of the structured nature of tracing events, in order to log structured information about the different events that occur.
Fixes: #186
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
> feat: structured tracing events

- .github/workflows/lint.yml
- .github/workflows/release.yml
> ci: configure nix github token

- templates/idx.html
Add AMD on AWS as a platform
Closes #222 
> feat: add AMD on AWS

- templates/idx.html
Signed-off-by: Dmitri Pal <dmitri@profian.com>
Addresses #252
> fix: append the correct port to the URL

- src/examples.rs
- templates/idx.html
Add Azure platform and .NET demos: ICUMonitor and ConfidentialTrading.
> feat: add Azure platform and .NET demos
